# Generated by Django 5.2.11 on 2026-02-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_internalmark_average_internal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalmark',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='internalmark',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FinalGrade',
        ),
        migrations.DeleteModel(
            name='InternalMark',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
