# Generated by Django 5.2.11 on 2026-02-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
