# Generated by Django 5.2.11 on 2026-02-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalmark',
            name='average_internal',
        ),
        migrations.AlterField(
            model_name='finalgrade',
            name='grade_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='internalmark',
            name='assignment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internalmark',
            name='attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='internalmark',
            name='test1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internalmark',
            name='test2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
