# Generated by Django 5.2.11 on 2026-02-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes_attended',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_classes',
        ),
    ]
