# Generated by Django 5.2.11 on 2026-02-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_classes_attended_student_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
